### ISSUE TITLE
Dead code in `/vm`?

### ISSUE THREAD

**Issue by makuru-org** [astro/skyflake#11]
It gets loaded into `/etc/skyflake/vm` but why, @astro? 
https://github.com/astro/skyflake/blob/40fb7a4fb248691014ba5b2c841f77a34d160a80/nixos-modules/ssh-deploy.nix#L232

How is someone meant to use the options defined in below file? It cant even show up in `nix repl`
https://github.com/astro/skyflake/blob/40fb7a4fb248691014ba5b2c841f77a34d160a80/vm/customization-options.nix#L3

**Comment by astro** [comment]
To keep it around for the ssh-deploy hook: https://github.com/astro/skyflake/blob/40fb7a4fb248691014ba5b2c841f77a34d160a80/nixos-modules/ssh-deploy.nix#L68
